### ISSUE TITLE
conda installation?

### ISSUE THREAD

**Issue by srib** [kinverarity1/lasio#231]
May I suggest making an option of a conda installation option available?

If this is of interest to you, I can submit a PR.

**Comment by kinverarity1** [comment]
Manually done! See https://anaconda.org/kinverarity/lasio

I will have to work out a travis setup for doing it automatically.

**Comment by johnvanv** [comment]
I would like to build a conda package for v0.25.1. 
The recipe you used for v0.24.1 seems like a good starting point but I can't find it in the repo. Could you point me to it? Thanks.

**Comment by kinverarity1** [comment]
Thanks for offering to help! I wish I knew where it was: I'm not sure. I'll have a look on my other computer tomorrow.

**Comment by mifarse** [comment]
Any updates on the issue? The current release version was uploaded to conda 2 years and 4 months ago

**Comment by kinverarity1** [comment]
No updates - I have tried to make conda recipes and not had any success or a particular need for it now that pip and conda play together better. Any help would be welcome on this front - if I have a working recipe I can try and add it to conda-forge.

**Comment by kinverarity1** [comment]
I've submitted a PR for conda-forge here: https://github.com/conda-forge/staged-recipes/pull/24515

I notice that anaconda themselves seem to be maintaining a recipe here: https://anaconda.org/services/lasio

I also updated my own channel here: https://anaconda.org/kinverarity/lasio

The meta.yaml that I used to do the last build (and have used for the conda-forge PR) is:

```
{% set name = "lasio" %}
{% set version = "0.31" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5dd3c4baa3f2c89bc95ca8e052dc37fe86363c687199c93fd0fae80c597e63e5

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - las2excel = lasio.excel:main
    - las2excelbulk = lasio.excel:main_bulk
    - lasversionconvert = lasio.convert_version:convert_version
    - lasio = lasio:version

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools_scm
  run:
    - python >=3.7
    - numpy
    - pandas
    - chardet
    - openpyxl

test:
  imports:
    - lasio

about:
  home: "https://github.com/kinverarity1/lasio"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Read/write well data from Log ASCII Standard (LAS) files"

extra:
  recipe-maintainers:
    - kinverarity1
```
